server:
  port: 8003
spring:
  application:
    name: server-c
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://wangguo:wangguo@registerA:8001/eureka/,http://wangguo:wangguo@registerB:8002/eureka/
  instance:
    hostname: registerC
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000

security:
  user:
    password: wangguo
    name: wangguo
  basic:
    enabled: true