server:
  port: 8002
spring:
  application:
    name: register-b
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://wangguo:wangguo@registerA:8001/eureka/,http://wangguo:wangguo@registerC:8003/eureka/
  instance:
    hostname: registerB
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
security:
  user:
    password: wangguo
    name: wangguo
  basic:
    enabled: true

