server:
  port: 8006
spring:
  application:
    name: provider-user
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql
  logging:
    level:
      root: INFO
      org.hibernate: INFO
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE
      org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
      com.itmuch.youran.persistence: ERROR
eureka:
  client:
    service-url:
       defaultZone: http://localhost:8001/eureka/,http://localhost:8002/eureka/,http://localhost:8003/eureka/
  instance:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 30
    hostname: provider-user


battcn:
  security:
    token:
      expiration-time:  10 # 分钟 1440
      refresh-exp-time: 30 # 分钟 2880
      issuer: http://www.gofobao.com
      signing-key: battcn




