server:
  port: 8007
spring:
  application:
    name: provider-user
  datasource:
      type: com.zaxxer.hikari.HikariDataSource
      username: root
      password: gt123456
      url: jdbc:mysql://113.106.202.51:3306/tx_db2?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&&useSSL=true
      driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    database: mysql
    show-sql: true
    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQL5Dialect
  cloud:
    consul:
      port: 8500
      host: localhost
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.itmuch.youran.persistence: ERROR
#eureka:
#  client:
#    service-url:
 #      defaultZone: http://localhost:8001/eureka
 # instance:
  #  lease-expiration-duration-in-seconds: 30
   # lease-renewal-interval-in-seconds: 30

txmanager:
  url: http://127.0.0.1:8899/tx/manager/
feign:
  hystrix:
    enabled: true
