server:
    port: 8010
spring:
  application:
    name: test-feign
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
logging:
  level: debug
feign:
  hystrix:
    enabled: true